name: "\U0001F41B Bug report"
description: Something's not working
labels: ['bug']
assignees: misaon
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: 🐛 The bug
      description: What isn't working? Describe what the bug is.
  - type: textarea
    validations:
      required: true
    attributes:
      label: 🌈 Expected behaviour
      description: What did you expect to happen?
  - type: textarea
    attributes:
      label: ℹ️ Additional context
      description: Add any other context about the problem here.
